[[buildpacks]]
id = "plow/r"
uri = "./buildpacks/r"
version = "0.1.0"

[[buildpacks]]
id = "plow/renv"
uri = "./buildpacks/renv"
version = "0.1.0"

[[buildpacks]]
id = "plow/shiny"
uri = "./buildpacks/shiny"
version = "0.1.0"

[[order]]
[[order.group]]
id = "plow/r"
version = "0.1.0"

[[order.group]]
id = "plow/renv"
version = "0.1.0"
optional = true

[[order.group]]
id = "plow/shiny"
version = "0.1.0"

[build]
image = "plow-build:avocado"

[run]
[[run.images]]
image = "plow-run:avocado"
