[[buildpacks]]
uri = "../buildpacks/r"

[[buildpacks]]
uri = "../buildpacks/renv"

[[buildpacks]]
uri = "../buildpacks/shiny"

# Shiny
[[order]]
  [[order.group]]
  id = "plow/r"
  version = "0.1.0"

  [[order.group]]
  id = "plow/renv"
  version = "0.1.0"
  optional = true

  [[order.group]]
  id = "plow/shiny"
  version = "0.1.0"

[stack]
id = "com.lytol.plow.ubuntu22"
run-image = "plow/stack-ubuntu22:run"
build-image = "plow/stack-ubuntu22:build"
